[package]
name = "daisy_days"
version = "0.1.0"
edition = "2021"
authors = ["Ahmad Hamdi"]

[[bin]]
name = "daisy_days"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
